server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:mysql://rm-bp1d66n2k7vagd1p3wo.mysql.rds.aliyuncs.com:3306/upc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
#    username: upc
#    password: Wx7712238*
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  configuration:
    map-underscore-to-camel-case: true


